version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_laptopshop
    restart: always
    environment:
      MYSQL_DATABASE: laptopshop
      MYSQL_ROOT_PASSWORD: 251105
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    image: your-springboot-app-image # <-- Thay bằng tên image Spring Boot bạn đã build
    container_name: springboot_laptopshop
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/laptopshop?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 251105
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

volumes:
  mysql_data:
